package alert

import (
	"fmt"
	"net/smtp"
	"sort"
	"strings"
	"time"

	"github.com/tpt-av/tpt-av/internal/config"
	"github.com/tpt-av/tpt-av/internal/events"
)

// WeeklyDigest sends a summary email of the past week's security events.
type WeeklyDigest struct {
	cfg      config.AlertConfig
	evLogPath string
}

func NewWeeklyDigest(cfg config.AlertConfig, evLogPath string) *WeeklyDigest {
	return &WeeklyDigest{cfg: cfg, evLogPath: evLogPath}
}

// Send collects the last 7 days of events and emails the digest.
func (d *WeeklyDigest) Send() error {
	if d.cfg.SMTPHost == "" || len(d.cfg.Recipients) == 0 {
		return nil
	}

	since := time.Now().UTC().Add(-7 * 24 * time.Hour)
	evts, err := events.ReadSince(d.evLogPath, since)
	if err != nil {
		return fmt.Errorf("reading events: %w", err)
	}

	subject := fmt.Sprintf("[TPT-AV] Weekly Security Digest — %s", time.Now().Format("Jan 2, 2006"))
	body := d.buildBody(evts)
	return d.send(subject, body)
}

func (d *WeeklyDigest) buildBody(evts []events.Event) string {
	var sb strings.Builder

	counts := map[string]int{}
	typeCounts := map[string]int{}
	var criticals []events.Event

	for _, e := range evts {
		counts[string(e.Severity)]++
		typeCounts[e.Type]++
		if e.Severity == events.Critical {
			criticals = append(criticals, e)
		}
	}

	sb.WriteString("TPT-AV Weekly Security Digest\n")
	sb.WriteString(strings.Repeat("=", 40) + "\n\n")
	sb.WriteString(fmt.Sprintf("Period:  last 7 days (up to %s)\n", time.Now().Format(time.RFC1123)))
	sb.WriteString(fmt.Sprintf("Total events: %d\n\n", len(evts)))

	sb.WriteString("── Summary by Severity ──\n")
	for _, sev := range []string{"critical", "warn", "info", "debug"} {
		if n := counts[sev]; n > 0 {
			sb.WriteString(fmt.Sprintf("  %-10s %d\n", sev, n))
		}
	}

	sb.WriteString("\n── Top Event Types ──\n")
	type kv struct{ k string; v int }
	var sorted []kv
	for k, v := range typeCounts {
		sorted = append(sorted, kv{k, v})
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].v > sorted[j].v })
	for i, item := range sorted {
		if i >= 10 {
			break
		}
		sb.WriteString(fmt.Sprintf("  %-30s %d\n", item.k, item.v))
	}

	if len(criticals) > 0 {
		sb.WriteString("\n── Critical Events ──\n")
		for _, e := range criticals {
			sb.WriteString(fmt.Sprintf("  [%s] %s  %s\n",
				e.TS.Format("Jan 02 15:04"), e.Type,
				formatData(e.Data)))
		}
	} else {
		sb.WriteString("\n✓ No critical events this week.\n")
	}

	sb.WriteString("\n──\nGenerated by TPT-AV\n")
	return sb.String()
}

func formatData(data map[string]string) string {
	if len(data) == 0 {
		return ""
	}
	parts := make([]string, 0, len(data))
	for k, v := range data {
		parts = append(parts, k+"="+v)
	}
	sort.Strings(parts)
	return strings.Join(parts, " ")
}

func (d *WeeklyDigest) send(subject, body string) error {
	hostPort := d.cfg.SMTPHost
	parts := strings.SplitN(hostPort, ":", 2)
	host := parts[0]

	var auth smtp.Auth
	if d.cfg.SMTPUser != "" {
		auth = smtp.PlainAuth("", d.cfg.SMTPUser, d.cfg.SMTPPass, host)
	}

	msg := fmt.Sprintf(
		"From: %s\r\nTo: %s\r\nSubject: %s\r\n\r\n%s",
		d.cfg.SMTPUser,
		strings.Join(d.cfg.Recipients, ", "),
		subject,
		body,
	)
	return smtp.SendMail(hostPort, auth, d.cfg.SMTPUser, d.cfg.Recipients, []byte(msg))
}
